export const bmw = [
  {
    img: './images/seperate/bmw/10.webp',
    price: 'STARTING FROM 70.2 LAKHS',
    model: 'BMW iX',
    pricecount: '֏ 35,000,000',
    mileage: '17.8 km/L',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: '765Nm',
    power: '516 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-iX/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-iX/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/9.webp',
    price: 'STARTING FROM 65.5 LAKHS',
    model: 'BMW 5 Series',
    pricecount: '֏ 30,000,000',
    mileage: '15.6 km/L',
    variant: 'Petrol',
    engineCc: '1998 cc',
    torque: '400Nm',
    power: '248 bhp',
    seatingCapacity: '5',
    Drivetype: 'RWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/5-series/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-5-Series/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/8.webp',
    price: 'STARTING FROM 56.8 LAKHS',
    model: 'BMW X3',
    pricecount: '֏ 28,000,000',
    mileage: '16.3 km/L',
    variant: 'Diesel',
    engineCc: '1998 cc',
    torque: '400Nm',
    power: '187 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X3/1675745866/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X3/1675745866/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/7.webp',
    price: 'STARTING FROM 47.2 LAKHS',
    model: 'BMW 3 Series',
    pricecount: '֏ 25,000,000',
    mileage: '15.9 km/L',
    variant: 'Petrol',
    engineCc: '1998 cc',
    torque: '400Nm',
    power: '255 bhp',
    seatingCapacity: '5',
    Drivetype: 'RWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-3-Series/1675685692/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-3-Series/1675685692/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/6.webp',
    price: 'STARTING FROM 90.5 LAKHS',
    model: 'BMW i7',
    pricecount: '֏ 45,000,000',
    mileage: '17.2 km/L',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: '880Nm',
    power: '536 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-i7/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-i7/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/5.webp',
    price: 'STARTING FROM 78.9 LAKHS',
    model: 'BMW X5',
    pricecount: '֏ 40,000,000',
    mileage: '14.2 km/L',
    variant: 'Diesel',
    engineCc: '2993 cc',
    torque: '620Nm',
    power: '261 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X7/1675749881/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X5/1708065015/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/4.webp',
    price: 'STARTING FROM 95.8 LAKHS',
    model: 'BMW XM',
    pricecount: '֏ 50,000,000',
    mileage: '11.9 km/L',
    variant: 'Petrol',
    engineCc: '4395 cc',
    torque: '800Nm',
    power: '625 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X7/1675749881/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-XM/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/3.webp',
    price: 'STARTING FROM 40.5 LAKHS',
    model: 'BMW X1',
    pricecount: '֏ 25,000,000',
    mileage: '18.1 km/L',
    variant: 'Petrol',
    engineCc: '1998 cc',
    torque: '280Nm',
    power: '187 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X7/1675749881/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X1/1677910541/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/2.webp',
    price: 'STARTING FROM 62.3 LAKHS',
    model: 'BMW Z4',
    pricecount: '֏ 35,000,000',
    mileage: '14.9 km/L',
    variant: 'Petrol',
    engineCc: '2998 cc',
    torque: '500Nm',
    power: '254 bhp',
    seatingCapacity: '2',
    Drivetype: 'RWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X7/1675749881/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X1/1677910541/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/1.webp',
    price: 'STARTING FROM 80.2 LAKHS',
    model: 'BMW X7',
    pricecount: '֏ 45,000,000',
    mileage: '12.6 km/L',
    variant: 'Diesel',
    engineCc: '2993 cc',
    torque: '700Nm',
    power: '335 bhp',
    seatingCapacity: '7',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X7/1675749881/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X1/1677910541/Exterior.html?hotSpotNonApp=yes'
  }
];
export const tata = [
  {
    img: './images/seperate/tata/tigor_ev.webp',
    price: 'STARTING FROM 11.2 LAKHS',
    model: 'Tata Tigor EV',
    pricecount: '֏ 10,000,000',
    mileage: '306 km/charge',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: '170Nm',
    power: '74 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Tigor/1630496142/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/tigor.webp',
    price: 'STARTING FROM 6.5 LAKHS',
    model: 'Tata Tigor',
    pricecount: '֏ 6,000,000',
    mileage: '20.3 km/L',
    variant: 'Petrol',
    engineCc: '1199 cc',
    torque: '113Nm',
    power: '84 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tigor/1609827993/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Tigor/1630496142/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/tiago_ev.webp',
    price: 'STARTING FROM 9.8 LAKHS',
    model: 'Tata Tiago EV',
    pricecount: '֏ 9,000,000',
    mileage: '306 km/charge',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: '140Nm',
    power: '86 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Tiago-EV/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/nexon_ev.webp',
    price: 'STARTING FROM 14.2 LAKHS',
    model: 'Tata Nexon EV',
    pricecount: '֏ 13,000,000',
    mileage: '312 km/charge',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: '245Nm',
    power: '127 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Nexon-EV/1697705255/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/altroz.webp',
    price: 'STARTING FROM 7.2 LAKHS',
    model: 'Tata Altroz',
    pricecount: '֏ 7,000,000',
    mileage: '25.11 km/L',
    variant: 'Petrol',
    engineCc: '1199 cc',
    torque: '113Nm',
    power: '85 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Altroz/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/tiago.webp',
    price: 'STARTING FROM 5.5 LAKHS',
    model: 'Tata Tiago',
    pricecount: '֏ 5,000,000',
    mileage: '23.84 km/L',
    variant: 'Petrol',
    engineCc: '1199 cc',
    torque: '113Nm',
    power: '84 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Nexon-EV/1697705255/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/safari.webp',
    price: 'STARTING FROM 15.5 LAKHS',
    model: 'Tata Safari',
    pricecount: '֏ 15,000,000',
    mileage: '16.14 km/L',
    variant: 'Diesel',
    engineCc: '1956 cc',
    torque: '350Nm',
    power: '168 bhp',
    seatingCapacity: '6/7',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Safari/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/punch_ev.webp',
    price: 'STARTING FROM 8.2 LAKHS',
    model: 'Tata Punch EV',
    pricecount: '֏ 8,000,000',
    mileage: 'N/A',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: 'N/A',
    power: 'N/A',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: 'N/A',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Punch-EV/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/harrier.webp',
    price: 'STARTING FROM 16.8 LAKHS',
    model: 'Tata Harrier',
    pricecount: '֏ 16,000,000',
    mileage: '16.35 km/L',
    variant: 'Diesel',
    engineCc: '1956 cc',
    torque: '350Nm',
    power: '168 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Harrier/1702960134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/nexon.webp',
    price: 'STARTING FROM 8.5 LAKHS',
    model: 'Tata Nexon',
    pricecount: '֏ 8,000,000',
    mileage: '22.4 km/L',
    variant: 'Petrol',
    engineCc: '1199 cc',
    torque: '170Nm',
    power: '118 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Nexon/1702960134/Exterior.html?hotSpotNonApp=yes'
  }
];

export const landRover = [
  {
    img: './images/seperate/landrover/eq.webp',
    price: 'STARTING FROM 67.2 LAKHS',
    model: 'Land Rover Range Rover Evoque',
    pricecount: '֏ 65,000,000',
    mileage: '15.68 km/L',
    variant: 'Petrol',
    engineCc: '1997 cc',
    torque: '365Nm',
    power: '246 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/evoque/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Land-Rover/Land-Rover-Range-Rover-Evoque/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/landrover/sports.webp',
    price: 'STARTING FROM 89.5 LAKHS',
    model: 'Land Rover Range Rover Sport',
    pricecount: '֏ 85,000,000',
    mileage: '13.33 km/L',
    variant: 'Diesel',
    engineCc: '2993 cc',
    torque: '650Nm',
    power: '296 bhp',
    seatingCapacity: '5/7',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/sport/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Land-Rover/Land-Rover-Range-Rover-Sport/1653567357/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/landrover/range-rover-velar.webp',
    price: 'STARTING FROM 80.8 LAKHS',
    model: 'Land Rover Range Rover Velar',
    pricecount: '֏ 75,000,000',
    mileage: '16.4 km/L',
    variant: 'Diesel',
    engineCc: '1997 cc',
    torque: '430Nm',
    power: '246 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/velar/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Land-Rover/Land-Rover-Range-Rover-Velar/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/landrover/rangerover.webp',
    price: 'STARTING FROM 105.2 LAKHS',
    model: 'Land Rover Range Rover',
    pricecount: '֏ 100,000,000',
    mileage: '12.8 km/L',
    variant: 'Diesel',
    engineCc: '2993 cc',
    torque: '650Nm',
    power: '296 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/range-rover/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Land-Rover/Land-Rover-Range-Rover/1676525435/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/landrover/defender.webp',
    price: 'STARTING FROM 76.5 LAKHS',
    model: 'Land Rover Defender',
    pricecount: '֏ 70,000,000',
    mileage: '14.5 km/L',
    variant: 'Diesel',
    engineCc: '1999 cc',
    torque: '430Nm',
    power: '296 bhp',
    seatingCapacity: '5/6/7',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/defender/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Land-Rover/Land-Rover-Defender/Exterior.html?hotSpotNonApp=yes'
  }
];



export const jaguar = [
  {
    img: './images/seperate/jaguar/i_pace.webp',
    price: 'STARTING FROM 25,510,000 AMD',
    model: 'Jaguar I-PACE',
    pricecount: '25,510,000 AMD',
    mileage: '470 km/full charge',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: '696Nm',
    power: '394 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/i-pace/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Jaguar/Jaguar-F-Pace/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/jaguar/i_pace.webp',
    price: 'STARTING FROM 20,590,000 AMD',
    model: 'Jaguar E-PACE',
    pricecount: '20,590,000 AMD',
    mileage: '15.2 km/L',
    variant: 'Petrol',
    engineCc: '1997 cc',
    torque: '365Nm',
    power: '246 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/e-pace/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Jaguar/Jaguar-F-Pace/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/jaguar/f_pace.webp',
    price: 'STARTING FROM 25,510,000 AMD',
    model: 'Jaguar F-PACE',
    pricecount: '25,510,000 AMD',
    mileage: '14.5 km/L',
    variant: 'Diesel',
    engineCc: '1997 cc',
    torque: '365Nm',
    power: '246 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/f-pace/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Jaguar/Jaguar-F-Pace/Exterior.html?hotSpotNonApp=yes'
  }
];
export const volvo = [
  {
    img: './images/seperate/volvo/xc40.webp',
    price: 'STARTING FROM 15,060,000 AMD',
    model: 'Volvo XC60',
    pricecount: '15,060,000 AMD',
    mileage: '18.0 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '1969 cc',
    torque: '300Nm',
    power: '190 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/xc40/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volvo/Volvo-XC40/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/volvo/xc90.webp',
    price: 'STARTING FROM 16,750,000 AMD',
    model: 'Volvo S60',
    pricecount: '16,750,000 AMD',
    mileage: '16.8 km/L',
    variant: 'Petrol / Hybrid',
    engineCc: '1969 / 1969 cc',
    torque: '300 / 350Nm',
    power: '190 / 303 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD / AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/s60/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volvo/Volvo-S60/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/volvo/xc60.webp',
    price: 'STARTING FROM 22,230,000 AMD',
    model: 'Volvo XC60',
    pricecount: '22,230,000 AMD',
    mileage: '11.2 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '1969 / 1969 cc',
    torque: '350 / 420Nm',
    power: '250 / 235 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/xc60/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volvo/Volvo-XC60/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/volvo/xc90.webp',
    price: 'STARTING FROM 32,810,000 AMD',
    model: 'Volvo XC90',
    pricecount: '32,810,000 AMD',
    mileage: '42.0 km/L',
    variant: 'Petrol / Hybrid',
    engineCc: '1969 / 1969 cc',
    torque: '300 / 350Nm',
    power: '190 / 303 bhp',
    seatingCapacity: '6/7',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/xc90/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volvo/Volvo-XC90/1692872134/Exterior.html?hotSpotNonApp=yes'
  }
];

export const skoda = [
  {
    img: './images/seperate/skoda/kushaq.webp',
    price: 'STARTING FROM 3,830,000 AMD',
    model: 'Skoda Kushaq',
    pricecount: '3,830,000 AMD',
    mileage: '17.88 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '999 / 1498 cc',
    torque: '175 / 250Nm',
    power: '115 / 113 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/kushaq/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Skoda/Skoda-Kushaq/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/skoda/rapid.webp',
    price: 'STARTING FROM 2,990,000 AMD',
    model: 'Skoda Rapid',
    pricecount: '2,990,000 AMD',
    mileage: '18.97 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '999 / 1498 cc',
    torque: '175 / 250Nm',
    power: '110 / 113 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://example.com/360-view/rapid/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Skoda/Skoda-Kushaq/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/skoda/octavia.webp',
    price: 'STARTING FROM 9,490,000 AMD',
    model: 'Skoda Octavia',
    pricecount: '9,490,000 AMD',
    mileage: '15.81 km/L',
    variant: 'Petrol',
    engineCc: '1984 cc',
    torque: '320Nm',
    power: '187 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/octavia/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Skoda/Skoda-Kushaq/Exterior.html?hotSpotNonApp=yes'
  }
];
export const kia = [
  {
    img: './images/seperate/kia/carens.webp',
    price: 'STARTING FROM 3,830,000 AMD',
    model: 'Kia Carens',
    pricecount: '3,830,000 AMD',
    mileage: '18.5 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '1497 / 1493 cc',
    torque: '144 / 250Nm',
    power: '113 / 113 bhp',
    seatingCapacity: '6/7',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://example.com/360-view/carens/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Kia/Kia-EV6/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/kia/Kia Seltos EV.webp',
    price: 'STARTING FROM 6,640,000 AMD',
    model: 'Kia Seltos EV',
    pricecount: '6,640,000 AMD',
    mileage: '450 km/full charge',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: 'N/A',
    power: '201 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/seltos-ev/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Kia/Kia-EV6/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/kia/carnival.webp',
    price: 'STARTING FROM 8,760,000 AMD',
    model: 'Kia Carnival',
    pricecount: '8,760,000 AMD',
    mileage: '13.9 km/L',
    variant: 'Diesel',
    engineCc: '2199 cc',
    torque: '440Nm',
    power: '197 bhp',
    seatingCapacity: '7/8',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/carnival/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Kia/Kia-Seltos/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/kia/sonet.webp',
    price: 'STARTING FROM 2,480,000 AMD',
    model: 'Kia Sonet',
    pricecount: '2,480,000 AMD',
    mileage: '24.1 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '998 / 1493 cc',
    torque: '172 / 250Nm',
    power: '118 / 113 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://example.com/360-view/sonet/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Kia/Kia-Seltos/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/kia/seltos.webp',
    price: 'STARTING FROM 3,610,000 AMD',
    model: 'Kia Seltos',
    pricecount: '3,610,000 AMD',
    mileage: '16.1 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '1497 / 1493 cc',
    torque: '144 / 250Nm',
    power: '113 / 113 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/seltos/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Kia/Kia-Seltos/Exterior.html?hotSpotNonApp=yes'
  }
];
export const porschee = [
  {
    img: './images/seperate/porsche/911.webp',
    price: 'STARTING FROM 31,000,000 AMD',
    model: 'Porsche 718 Cayman',
    pricecount: '31,000,000 AMD',
    mileage: '13.8 km/L',
    variant: 'Petrol',
    engineCc: '1988 cc',
    torque: '420Nm',
    power: '295 bhp',
    seatingCapacity: '2',
    Drivetype: 'RWD',
    NCAPsafetyrating: 'Not Rated',
    iframeInterior: 'https://example.com/360-view/718-cayman/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Porsche/Porsche-Taycan/1677666193/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/porsche/taycan.webp',
    price: 'STARTING FROM 54,750,000 AMD',
    model: 'Porsche Taycan',
    pricecount: '54,750,000 AMD',
    mileage: '420 km/full charge',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: 'N/A',
    power: '469 bhp',
    seatingCapacity: '4/5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/taycan/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Porsche/Porsche-Taycan/1677666193/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/porsche/macan.webp',
    price: 'STARTING FROM 25,550,000 AMD',
    model: 'Porsche Macan',
    pricecount: '25,550,000 AMD',
    mileage: '11.23 km/L',
    variant: 'Petrol',
    engineCc: '1984 cc',
    torque: '430Nm',
    power: '248 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/macan/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Porsche/Porsche-Macan/1677654929/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/porsche/cayenne.webp',
    price: 'STARTING FROM 43,800,000 AMD',
    model: 'Porsche Cayenne',
    pricecount: '43,800,000 AMD',
    mileage: '9.6 km/L',
    variant: 'Petrol / Hybrid',
    engineCc: '2995 / 2995 cc',
    torque: '450 / 700Nm',
    power: '335 / 460 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: 'Not Rated',
    iframeInterior: 'https://example.com/360-view/cayenne/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Porsche/Porsche-Cayenne/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/porsche/panmera.webp',
    price: 'STARTING FROM 54,750,000 AMD',
    model: 'Porsche Panamera',
    pricecount: '54,750,000 AMD',
    mileage: '14.7 km/L',
    variant: 'Petrol / Hybrid',
    engineCc: '2995 / 2894 cc',
    torque: '450 / 700Nm',
    power: '335 / 456 bhp',
    seatingCapacity: '4/5',
    Drivetype: 'AWD',
    NCAPsafetyrating: 'Not Rated',
    iframeInterior: 'https://example.com/360-view/panamera/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Porsche/Porsche-Panamera/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/porsche/911.webp',
    price: 'STARTING FROM 80,300,000 AMD',
    model: 'Porsche 911',
    pricecount: '80,300,000 AMD',
    mileage: '8.0 km/L',
    variant: 'Petrol',
    engineCc: '3745 cc',
    torque: '530Nm',
    power: '444 bhp',
    seatingCapacity: '4',
    Drivetype: 'RWD',
    NCAPsafetyrating: 'Not Rated',
    iframeInterior: 'https://example.com/360-view/911/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Porsche/Porsche-911/1623734594/Exterior.html?hotSpotNonApp=yes'
  }
];
